<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyQuanKaraoke" Class="LinqNhanVienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-FI63BATD;Initial Catalog=QuanLyQuanKaraoke;Persist Security Info=True;User ID=sa" SettingsObjectName="QuanLyQuanKaraoke.Properties.Settings" SettingsPropertyName="QuanLyQuanKaraokeConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>